--
-- PostgreSQL database dump
--

\restrict 1mBeyt7OJbg8lojKLLjAlu8gYlIEmUWRit5ItxD8hwT6Q5Ceqjfn493hMvR6VuR

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_items (
    id bigint NOT NULL,
    auth_mark character varying(255),
    title character varying(255),
    meta_id bigint
);


--
-- Name: auth_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_items (id, auth_mark, title, meta_id) FROM stdin;
\.


--
-- Name: auth_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_items_id_seq', 1, false);


--
-- Name: auth_items auth_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_items
    ADD CONSTRAINT auth_items_pkey PRIMARY KEY (id);


--
-- Name: auth_items fkoe94opdx0lmejovcssjy9r8sv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_items
    ADD CONSTRAINT fkoe94opdx0lmejovcssjy9r8sv FOREIGN KEY (meta_id) REFERENCES public.route_meta(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 1mBeyt7OJbg8lojKLLjAlu8gYlIEmUWRit5ItxD8hwT6Q5Ceqjfn493hMvR6VuR

