--
-- PostgreSQL database dump
--

\restrict 0JhFjIGbaGQHT4BKoDOf0BFQeNiU8lydWD7u2fmGyP5n84j0G3qdHvQTcVhtfGX

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    code character varying(255),
    description character varying(255),
    enabled boolean,
    leader_id bigint,
    leader_name character varying(255),
    name character varying(255),
    sort integer,
    parent_id bigint,
    attendance_rule_id bigint
);


--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.departments (id, code, description, enabled, leader_id, leader_name, name, sort, parent_id, attendance_rule_id) FROM stdin;
185	3facb9d7c5883910	\N	t	\N	\N	总经理	\N	\N	\N
186	3feeeff9345fbf37	\N	t	\N	\N	管理者代表	\N	185	\N
187	3fa246ba15572b70	\N	t	\N	\N	副总经理(分管行政财务)	\N	185	\N
188	3fdbed14e6bbce08	\N	t	\N	\N	财务部	\N	187	\N
189	3fc48a6536061fa0	\N	t	\N	\N	行政部	\N	187	\N
190	3febab4e5db5b2d9	\N	t	\N	\N	食堂	\N	189	\N
191	3fea57e95ce0fc53	\N	t	\N	\N	设备部	\N	187	\N
192	3fd6a8c3c6875092	\N	t	\N	\N	信息技术部	\N	187	\N
193	3fc1f00cb8bb4998	\N	t	\N	\N	副总经理(分管工程)	\N	185	\N
194	3fd3054030ddbd50	\N	t	\N	\N	工程部	\N	193	\N
195	3fede5cd35b914b5	\N	t	\N	\N	副总经理(分管生产计划)	\N	185	\N
196	3fec90c5d29016be	\N	t	\N	\N	计划采购部	\N	195	\N
197	3f98c3dbf25644a0	\N	t	\N	\N	仓库	\N	196	\N
198	3fe5dacbfc5a934d	\N	t	\N	\N	品管部	\N	195	\N
199	3fe914baafc550ec	\N	t	\N	\N	工艺部	\N	195	\N
200	3fdbca3b234b69f0	\N	t	\N	\N	生产部	\N	195	\N
201	3fd8de11c12ad816	\N	t	\N	\N	装配车间	\N	200	\N
202	3fc4c454757f98e0	\N	t	\N	\N	焊接车间	\N	200	\N
203	3fecd7131c98a8e8	\N	t	\N	\N	副总经理(分管结构)	\N	185	\N
204	3fe0967680ab8dfc	\N	t	\N	\N	结构部	\N	203	\N
205	3fe1d8c95f0b8c9b	\N	t	\N	\N	副总经理(分管技术)	\N	185	\N
206	3fe77061a177898f	\N	t	\N	\N	技术部	\N	205	\N
207	3fef23a154da9297	\N	t	\N	\N	副总经理(分管营销)	\N	185	\N
208	3fe507823e38186f	\N	t	\N	\N	外贸部	\N	207	\N
209	3feea728342d204f	\N	t	\N	\N	发运组	\N	208	\N
210	3fd656133a8a5d4a	\N	t	\N	\N	市场部	\N	207	\N
211	3fe5c2272c88eb73	\N	t	\N	\N	售后服务组	\N	210	\N
212	3fec264678f9cc4f	\N	t	\N	\N	副总经理(分管人资)	\N	185	\N
213	3fe89d83ec142266	\N	t	\N	\N	人力资源部	\N	212	\N
214	3fd9f2efed8e85dc	\N	t	\N	\N	质量管理办公室	\N	185	\N
\.


--
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.departments_id_seq', 215, true);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: departments fk63q917a0aq92i7gcw6h7f1jrv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fk63q917a0aq92i7gcw6h7f1jrv FOREIGN KEY (parent_id) REFERENCES public.departments(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 0JhFjIGbaGQHT4BKoDOf0BFQeNiU8lydWD7u2fmGyP5n84j0G3qdHvQTcVhtfGX

