--
-- PostgreSQL database dump
--

\restrict ZPE8z6BX1QE0kgyOLYiGNb8KaNjuCunoOVA4ZUhNi0n8Kif24zffT3lFMKBiNSB

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    create_time timestamp(6) without time zone,
    description character varying(255),
    enabled boolean,
    role_code character varying(255),
    role_name character varying(255),
    is_admin boolean
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (role_id, create_time, description, enabled, role_code, role_name, is_admin) FROM stdin;
1	\N	拥有系统所有权限	t	R_SUPER	超级管理员	t
2	\N	拥有系统大部分权限	t	R_ADMIN	管理员	t
3	\N	拥有系统基础权限	t	R_USER	普通用户	f
\.


--
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 6, true);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- PostgreSQL database dump complete
--

\unrestrict ZPE8z6BX1QE0kgyOLYiGNb8KaNjuCunoOVA4ZUhNi0n8Kif24zffT3lFMKBiNSB

