--
-- PostgreSQL database dump
--

\restrict XOwbrzaJAzD3MCRzoAj0kd6WNt9ryxtG2uyJvqQ9BD2Ynt53yBoNnu3pa0ylp4l

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: routes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.routes (
    id bigint NOT NULL,
    component character varying(255),
    name character varying(255),
    path character varying(255),
    meta_id bigint,
    parent_id bigint
);


--
-- Name: routes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: routes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.routes (id, component, name, path, meta_id, parent_id) FROM stdin;
779	/dashboard/console	Console	/dashboard	800	\N
780	/index/index	Personnel	/personnel	801	\N
781	/personnel/employee	Employee	employee	802	780
782	/system/salary	Salary	salary	803	780
783	/system/salary-statistics	SalaryStatistics	salary-statistics	804	780
784	/index/index	Organization	/organization	805	\N
785	/system/dept	Department	dept	806	784
786	/system/position	Position	position	807	784
787	/index/index	System	/system	808	\N
788	/system/user	User	user	809	787
789	/system/role	Role	role	810	787
790	/system/menu	Menus	menu	811	787
791	/index/index	Form	/form	812	\N
792	/form/application	FormApplication	application	813	791
793	/form/application/form-edit	FormApplicationEdit	edit	814	792
794	/form/approval	FormApproval	approval	815	791
795	/index/index	Attendance	/attendance	816	\N
796	/attendance/upload	AttendanceUpload	upload	817	795
797	/attendance/query	AttendanceQuery	query	818	795
798	/attendance/rule	AttendanceRule	rule	819	795
799	/attendance/schedule	AttendanceSchedule	schedule	820	795
800	/index/index	Ops	/ops	821	\N
801	/ops/server-monitor	ServerOps	server	822	800
802	/ops/system-log	SystemLogs	logs	823	800
804	/attendance/shift-type	ShiftType	shift-type	826	795
\.


--
-- Name: routes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.routes_id_seq', 804, true);


--
-- Name: routes routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- Name: routes ukt34bjs38w94b5koyapffnu794; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT ukt34bjs38w94b5koyapffnu794 UNIQUE (meta_id);


--
-- Name: routes fks2tl8xd1609kk9spmlsyn6505; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT fks2tl8xd1609kk9spmlsyn6505 FOREIGN KEY (meta_id) REFERENCES public.route_meta(id);


--
-- Name: routes fksakcky3a6u5rfpiflfyrgklwm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT fksakcky3a6u5rfpiflfyrgklwm FOREIGN KEY (parent_id) REFERENCES public.routes(id);


--
-- PostgreSQL database dump complete
--

\unrestrict XOwbrzaJAzD3MCRzoAj0kd6WNt9ryxtG2uyJvqQ9BD2Ynt53yBoNnu3pa0ylp4l

