--
-- PostgreSQL database dump
--

\restrict VG8Txi7AoGyNciFZHrKaAFex87J9ARetdYq9cFCg0TbJBJ5YnI1BX3OLgCOV2KY

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: route_meta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.route_meta (
    id bigint NOT NULL,
    active_path character varying(255),
    auth_mark character varying(255),
    fixed_tab boolean,
    icon character varying(255),
    is_auth_button boolean,
    is_first_level boolean,
    is_full_page boolean,
    is_hide boolean,
    is_hide_tab boolean,
    is_iframe boolean,
    keep_alive boolean,
    link character varying(255),
    parent_path character varying(255),
    show_badge boolean,
    show_text_badge character varying(255),
    title character varying(255),
    always_show boolean,
    sort_order integer
);


--
-- Name: route_meta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.route_meta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_meta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: route_meta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.route_meta (id, active_path, auth_mark, fixed_tab, icon, is_auth_button, is_first_level, is_full_page, is_hide, is_hide_tab, is_iframe, keep_alive, link, parent_path, show_badge, show_text_badge, title, always_show, sort_order) FROM stdin;
821	\N	\N	\N	ri:server-line	\N	\N	\N	\N	\N	\N	f	\N	\N	\N	\N	运维管理	\N	6
822	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	服务器运维	\N	1
823	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	系统日志	\N	1
800	\N	\N	t	ri:pie-chart-line	\N	\N	\N	\N	\N	\N	f	\N	\N	\N	\N	工作台	\N	1
801	\N	\N	\N	ri:user-star-line	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	人事管理	t	1
802	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	员工管理	\N	1
803	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	薪资管理	\N	1
804	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	薪酬统计	\N	1
805	\N	\N	\N	ri:building-line	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	组织架构	t	1
806	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	部门管理	\N	1
807	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	岗位管理	\N	1
808	\N	\N	\N	ri:settings-2-line	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	系统管理	\N	1
809	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	用户管理	\N	1
810	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	角色管理	\N	1
811	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	菜单管理	\N	1
812	\N	\N	\N	ri:file-list-line	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	表单管理	\N	1
813	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	表单申请	\N	1
814	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	f	\N	\N	\N	\N	新增申请	\N	1
815	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	表单审批	\N	1
816	\N	\N	\N	ri:time-line	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	考勤管理	\N	1
817	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	上传考勤	\N	1
818	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	考勤查询	\N	1
819	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	考勤规则	\N	1
820	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	排班管理	\N	1
826	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	\N	\N	\N	班别管理	\N	1
\.


--
-- Name: route_meta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.route_meta_id_seq', 826, true);


--
-- Name: route_meta route_meta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route_meta
    ADD CONSTRAINT route_meta_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict VG8Txi7AoGyNciFZHrKaAFex87J9ARetdYq9cFCg0TbJBJ5YnI1BX3OLgCOV2KY

