--
-- PostgreSQL database dump
--

\restrict YIheassxkRxhiPcgpte6oWtXvIwykYk38tVEGjBOKmUOBW4bLUR7QnqhhO4q6Dj

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: salaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.salaries (
    id bigint NOT NULL,
    amount character varying(255),
    create_by character varying(255),
    create_time timestamp(6) without time zone,
    current_salary character varying(255),
    initial_salary character varying(255),
    last_adjustment_date timestamp(6) without time zone,
    next_adjustment_date timestamp(6) without time zone,
    payment_cycle character varying(255),
    remark character varying(255),
    salary_type character varying(255),
    status character varying(255),
    update_by character varying(255),
    update_time timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: salaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.salaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: salaries; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.salaries (id, amount, create_by, create_time, current_salary, initial_salary, last_adjustment_date, next_adjustment_date, payment_cycle, remark, salary_type, status, update_by, update_time, user_id) FROM stdin;
\.


--
-- Name: salaries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.salaries_id_seq', 1, false);


--
-- Name: salaries salaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salaries
    ADD CONSTRAINT salaries_pkey PRIMARY KEY (id);


--
-- Name: salaries uk65x0hr7lif8m6c15yanah3jwn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salaries
    ADD CONSTRAINT uk65x0hr7lif8m6c15yanah3jwn UNIQUE (user_id);


--
-- Name: salaries fkos57j8u42tdn3d132be45fsh9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salaries
    ADD CONSTRAINT fkos57j8u42tdn3d132be45fsh9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict YIheassxkRxhiPcgpte6oWtXvIwykYk38tVEGjBOKmUOBW4bLUR7QnqhhO4q6Dj

