--
-- PostgreSQL database dump
--

\restrict c9XEK96OWKzR3zkVFA5aBjBeXd0uTMlWaWMteJ9tiXliYNWUu8eTcWVibfWfgdY

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: shift_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shift_types (
    id bigint NOT NULL,
    code character varying(255),
    color character varying(255),
    is_default boolean,
    is_rest boolean,
    name character varying(255),
    remark character varying(255),
    work_end character varying(255),
    work_start character varying(255)
);


--
-- Name: shift_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shift_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shift_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: shift_types; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shift_types (id, code, color, is_default, is_rest, name, remark, work_end, work_start) FROM stdin;
2	REST	#FF9F43	f	t	休息	休息日	\N	\N
3	NIGHT	#A29BFE	f	f	晚班	下午至晚间班次	22:00	14:00
1	MORNING	#4ECDC4	t	f	白班	标准工作班次	17:00	08:30
4	\N	#409EFF	f	f	test	\N	18:00	09:00
\.


--
-- Name: shift_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shift_types_id_seq', 4, true);


--
-- Name: shift_types shift_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shift_types
    ADD CONSTRAINT shift_types_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict c9XEK96OWKzR3zkVFA5aBjBeXd0uTMlWaWMteJ9tiXliYNWUu8eTcWVibfWfgdY

