--
-- PostgreSQL database dump
--

\restrict Q98HDncQbzfUh1f8w9HJc29nLjNTaqZnaopaG20DUgqKBCh8V6fm3vZIohvkfNh

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: user_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_credentials (
    id bigint NOT NULL,
    employee_id character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: user_credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: user_credentials; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_credentials (id, employee_id, password) FROM stdin;
1	EMP0003	123456
2	EMP0004	123456
3	EMP0005	123456
4	EMP0006	123456
5	EMP0007	123456
6	EMP0008	123456
7	EMP0009	123456
8	EMP0010	123456
9	EMP0011	123456
10	EMP0012	123456
11	EMP0013	123456
12	EMP0014	123456
13	EMP0015	123456
14	EMP0016	123456
15	EMP0017	123456
16	EMP0018	123456
17	EMP0019	123456
18	EMP0020	123456
19	EMP0021	123456
20	EMP0022	123456
21	EMP0023	123456
22	EMP0024	123456
23	EMP0025	123456
24	EMP0026	123456
25	EMP0027	123456
26	EMP0028	123456
27	EMP0029	123456
28	EMP0030	123456
29	EMP0031	123456
30	EMP0032	123456
31	EMP0033	123456
32	EMP0034	123456
33	EMP0035	123456
34	EMP0036	123456
35	EMP0037	123456
36	EMP0038	123456
37	EMP0039	123456
38	EMP0040	123456
39	EMP0041	123456
40	EMP0042	123456
41	EMP0043	123456
42	EMP0044	123456
43	EMP0045	123456
44	EMP0046	123456
45	EMP0047	123456
46	EMP0048	123456
47	EMP0049	123456
48	EMP0050	123456
49	EMP0051	123456
50	EMP0052	123456
51	EMP0053	123456
52	EMP0054	123456
53	EMP0001	123456
54	EMP0002	123456
55	20950	123456
56	EMP0059	123456
57	EMP0055	123456
58	EMP0056	123456
59	EMP0057	123456
60	EMP0058	123456
61	EMP0060	123456
62	SpuerAdmin	123456
63	SuperAdmin	123456
\.


--
-- Name: user_credentials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_credentials_id_seq', 63, true);


--
-- Name: user_credentials ukpti0msfxdtvhn2n89njxpn4se; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_credentials
    ADD CONSTRAINT ukpti0msfxdtvhn2n89njxpn4se UNIQUE (employee_id);


--
-- Name: user_credentials user_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_credentials
    ADD CONSTRAINT user_credentials_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict Q98HDncQbzfUh1f8w9HJc29nLjNTaqZnaopaG20DUgqKBCh8V6fm3vZIohvkfNh

