--
-- PostgreSQL database dump
--

\restrict 0zOw7ZLBdPWqZXeQrMcsghHgvMshyE32bm5fpLPkoEKgS41ko3j2WQdJHV2gFKL

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    role_id bigint,
    user_id bigint
);


--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_roles (id, role_id, user_id) FROM stdin;
434	1	368
435	3	368
437	1	13224
374	3	369
375	3	370
376	3	371
377	3	372
378	3	373
379	3	374
380	3	375
381	3	376
382	3	377
383	3	378
384	3	379
385	3	380
386	3	381
387	3	382
388	3	383
389	3	384
390	3	385
391	3	386
392	3	387
393	3	388
394	3	389
395	3	390
396	3	391
397	3	392
398	3	393
399	3	394
400	3	395
401	3	396
402	3	397
403	3	398
404	3	399
405	3	400
406	3	401
407	3	402
408	3	403
409	3	404
410	3	405
411	3	406
412	3	407
413	3	408
414	3	409
415	3	410
416	3	411
417	3	412
418	3	413
419	3	414
420	3	415
421	3	416
422	3	417
423	3	418
424	3	419
425	3	420
426	3	421
427	3	422
428	3	423
429	3	424
430	3	425
431	3	426
432	3	427
433	3	428
\.


--
-- Name: user_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_roles_id_seq', 437, true);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 0zOw7ZLBdPWqZXeQrMcsghHgvMshyE32bm5fpLPkoEKgS41ko3j2WQdJHV2gFKL

